const eventDate=new Date('2026-05-06T18:00:00');
function updateCountdown(){const now=new Date();const diff=eventDate-now;const ids=['days','hours','minutes','seconds'];const els=ids.map(id=>document.getElementById(id));if(els.some(el=>!el))return;if(diff<=0){els.forEach(el=>el.textContent='00');return;}const days=Math.floor(diff/(1000*60*60*24));const hours=Math.floor((diff/(1000*60*60))%24);const minutes=Math.floor((diff/(1000*60))%60);const seconds=Math.floor((diff/1000)%60);document.getElementById('days').textContent=String(days).padStart(2,'0');document.getElementById('hours').textContent=String(hours).padStart(2,'0');document.getElementById('minutes').textContent=String(minutes).padStart(2,'0');document.getElementById('seconds').textContent=String(seconds).padStart(2,'0');}
updateCountdown();setInterval(updateCountdown,1000);

const canvas=document.getElementById('particleCanvas');const ctx=canvas.getContext('2d');let particles=[];const particleCount=95;const palette=['rgba(111,232,255,0.65)','rgba(255,219,112,0.55)','rgba(155,123,255,0.45)','rgba(255,125,200,0.32)'];
function resizeCanvas(){canvas.width=window.innerWidth*window.devicePixelRatio;canvas.height=window.innerHeight*window.devicePixelRatio;canvas.style.width=`${window.innerWidth}px`;canvas.style.height=`${window.innerHeight}px`;ctx.setTransform(window.devicePixelRatio,0,0,window.devicePixelRatio,0,0);}
function createParticles(){particles=Array.from({length:particleCount},()=>({x:Math.random()*window.innerWidth,y:Math.random()*window.innerHeight,r:Math.random()*2.3+.5,vx:(Math.random()-.5)*.32,vy:(Math.random()-.5)*.32,color:palette[Math.floor(Math.random()*palette.length)]}));}
function animateParticles(){ctx.clearRect(0,0,window.innerWidth,window.innerHeight);for(const p of particles){p.x+=p.vx;p.y+=p.vy;if(p.x<-20)p.x=window.innerWidth+20;if(p.x>window.innerWidth+20)p.x=-20;if(p.y<-20)p.y=window.innerHeight+20;if(p.y>window.innerHeight+20)p.y=-20;ctx.beginPath();ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=16;ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();}for(let i=0;i<particles.length;i++){for(let j=i+1;j<particles.length;j++){const a=particles[i],b=particles[j];const dx=a.x-b.x,dy=a.y-b.y;const dist=Math.sqrt(dx*dx+dy*dy);if(dist<110){ctx.beginPath();ctx.strokeStyle=`rgba(111,232,255,${0.08*(1-dist/110)})`;ctx.lineWidth=1;ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}}}requestAnimationFrame(animateParticles);}
resizeCanvas();createParticles();animateParticles();window.addEventListener('resize',()=>{resizeCanvas();createParticles();});
